import { Evidence, ToolResult, fact, toolResult } from "./contracts";
import { getGrid, hotspotsTool, inspectTool } from "./tools";

const STATUS="DECISION_SUPPORT_HEURISTIC", SCOPE="RELATIVE_WITHIN_DEMO_AOI";
const LIMIT_ZH="该建议用于基于当前 HeatSafe Evidence 的行动优先级辅助，不代表措施实施后的风险下降幅度，也不构成未来情景预测。";
const LIMIT_EN="These recommendations support action prioritization from current HeatSafe Evidence. They do not estimate risk reduction after implementation or constitute a future scenario forecast.";
const WHO="https://www.who.int/europe/publications/i/item/9789289062930", UN="https://unhabitat.org/handbook-on-urban-heat-management-in-the-global-south";

const guidance:Record<string,any>={
 WHO_HHAP_2026_REDUCE_EXPOSURE:{guidance_id:"WHO_HHAP_2026_REDUCE_EXPOSURE",organization_zh:"世界卫生组织欧洲区域办事处",organization_en:"World Health Organization Regional Office for Europe",title_zh:"高温-健康行动计划：指南（第二版）",title_en:"Heat-health action plans: guidance, second edition",year:2026,section_zh:"减少室内外高温暴露",section_en:"Reduction in indoor and outdoor heat exposure",url:WHO},
 WHO_HHAP_2026_RISK_GROUPS:{guidance_id:"WHO_HHAP_2026_RISK_GROUPS",organization_zh:"世界卫生组织欧洲区域办事处",organization_en:"World Health Organization Regional Office for Europe",title_zh:"高温-健康行动计划：指南（第二版）",title_en:"Heat-health action plans: guidance, second edition",year:2026,section_zh:"重点照护脆弱人群",section_en:"Special care for vulnerable population groups",url:WHO},
 WHO_HHAP_2026_COMMUNICATION:{guidance_id:"WHO_HHAP_2026_COMMUNICATION",organization_zh:"世界卫生组织欧洲区域办事处",organization_en:"World Health Organization Regional Office for Europe",title_zh:"高温-健康行动计划：指南（第二版）",title_en:"Heat-health action plans: guidance, second edition",year:2026,section_zh:"高温相关信息与沟通",section_en:"Heat-related information and communication",url:WHO},
 UNHABITAT_UHM_2025_PASSIVE_COOLING:{guidance_id:"UNHABITAT_UHM_2025_PASSIVE_COOLING",organization_zh:"联合国人居署 / 世界银行 / 联合国环境署",organization_en:"UN-Habitat / World Bank / UNEP",title_zh:"全球南方城市高温管理手册",title_en:"Handbook on Urban Heat Management in the Global South",year:2025,section_zh:"被动降温与热韧性公共空间",section_en:"Passive cooling and heat-resilient public space",url:UN},
 UNHABITAT_UHM_2025_GREEN_INFRA:{guidance_id:"UNHABITAT_UHM_2025_GREEN_INFRA",organization_zh:"联合国人居署 / 世界银行 / 联合国环境署",organization_en:"UN-Habitat / World Bank / UNEP",title_zh:"全球南方城市高温管理手册",title_en:"Handbook on Urban Heat Management in the Global South",year:2025,section_zh:"绿蓝基础设施",section_en:"Green and blue infrastructure",url:UN},
 UNHABITAT_UHM_2025_SUSTAINABLE_COOLING:{guidance_id:"UNHABITAT_UHM_2025_SUSTAINABLE_COOLING",organization_zh:"联合国人居署 / 世界银行 / 联合国环境署",organization_en:"UN-Habitat / World Bank / UNEP",title_zh:"全球南方城市高温管理手册",title_en:"Handbook on Urban Heat Management in the Global South",year:2025,section_zh:"可持续降温与城市高温治理",section_en:"Sustainable cooling and urban heat governance",url:UN},
};

const catalog:Record<string,any>={
 HEAT_EXPOSURE_MITIGATION:{metric:"hazard_contribution_points",contexts:["lst_median_c"],title_zh:"热暴露缓解",title_en:"Heat Exposure Mitigation",actions_zh:["优先评估步行与公共活动空间的遮阴条件","在高温时段加强重点热区的公共空间热暴露管理","评估被动降温与低吸热表面的适用机会"],actions_en:["Prioritize assessment of shade in walking and public activity spaces","Strengthen hot-period public-space heat exposure management","Assess suitable passive-cooling and lower-heat-absorption options"],guidance_ids:["WHO_HHAP_2026_REDUCE_EXPOSURE","UNHABITAT_UHM_2025_PASSIVE_COOLING"]},
 POPULATION_EXPOSURE_MANAGEMENT:{metric:"exposure_contribution_points",contexts:["population_total"],title_zh:"人口暴露管理",title_en:"Population Exposure Management",actions_zh:["优先评估高人口暴露区域的避暑服务承载能力","加强高温信息与公共服务的覆盖和触达","规划高温重点时段的现场服务与人流管理"],actions_en:["Prioritize assessment of cooling-service capacity in highly exposed areas","Strengthen the reach of heat information and public services","Plan on-site services and crowd management for priority hot periods"],guidance_ids:["WHO_HHAP_2026_COMMUNICATION","UNHABITAT_UHM_2025_SUSTAINABLE_COOLING"]},
 VULNERABLE_POPULATION_PROTECTION:{metric:"vulnerability_contribution_points",contexts:["elderly_share","child_share"],title_zh:"脆弱人群保护",title_en:"Vulnerable Population Protection",actions_zh:["优先考虑老年人和儿童等重点人群的高温信息触达","加强社区主动联系与照护协同机制","评估重点人群获得避暑空间与健康服务的便利性"],actions_en:["Prioritize heat-information outreach for older adults, children, and other priority groups","Strengthen proactive community contact and care coordination","Assess priority groups' access to cooling spaces and health services"],guidance_ids:["WHO_HHAP_2026_RISK_GROUPS","WHO_HHAP_2026_COMMUNICATION"]},
 ADAPTIVE_CAPACITY_ENHANCEMENT:{metric:"adaptive_deficit_contribution_points",contexts:["green_fraction_land"],title_zh:"适应能力提升",title_en:"Adaptive Capacity Enhancement",actions_zh:["优先评估绿荫、树冠与连续遮阴条件","评估绿地和自然基础降温措施的适用机会","规划步行空间与公共服务节点的热环境改善"],actions_en:["Prioritize assessment of green shade, tree canopy, and continuous shade","Assess suitable green-infrastructure and nature-based cooling opportunities","Plan thermal-environment improvements for walking routes and public-service nodes"],guidance_ids:["UNHABITAT_UHM_2025_GREEN_INFRA","WHO_HHAP_2026_REDUCE_EXPOSURE"]},
};
const order=Object.keys(catalog);
const ref=(item:Evidence)=>({evidence_id:item.evidence_id??"",metric:item.metric,grid_id:item.grid_id,value:item.value});

export function gridActionsTool(gridId:string,limit=3):ToolResult {
  const grid=getGrid(gridId); if(grid.analysis_status!=="ANALYZABLE_LAND"||grid.risk_score==null)throw new Error("ACTION_PLAN_UNAVAILABLE_NON_URBAN_WATER");
  const underlying=inspectTool(gridId).evidence, byMetric=Object.fromEntries(underlying.map(item=>[item.metric,item]));
  const ranked=order.map((family,index)=>({family,index,value:Number(grid[catalog[family].metric])})).sort((a,b)=>b.value-a.value||a.index-b.index).slice(0,limit);
  const derived:Evidence[]=[fact("action_catalog_version","Action catalog version","M5C_ACTION_CATALOG_V1",{grid_id:gridId,source_component:"ACTION_ENGINE",method:"GROUNDED_ACTION_CATALOG_V1"}),fact("recommendation_status","Recommendation status",STATUS,{grid_id:gridId,source_component:"ACTION_ENGINE",method:"DETERMINISTIC_ACTION_PRIORITY_V1"})];
  const cards:any[]=[], guidanceIds:string[]=[];
  ranked.forEach(({family,value},index)=>{const entry=catalog[family], supporting=[byMetric[entry.metric],...entry.contexts.map((metric:string)=>byMetric[metric]).filter(Boolean)];guidanceIds.push(...entry.guidance_ids);cards.push({priority_rank:index+1,action_family:family,title_zh:entry.title_zh,title_en:entry.title_en,recommended_actions_zh:entry.actions_zh,recommended_actions_en:entry.actions_en,why_zh:`${entry.title_zh}的排序依据是现有 ${entry.metric} 加权贡献。`,why_en:`${entry.title_en} is prioritized using the existing weighted contribution from ${entry.metric}.`,signal_metric:entry.metric,signal_points:value,supporting_evidence:supporting.map(ref),guidance_ids:entry.guidance_ids,recommendation_status:STATUS,effect_estimate:null,limitation_zh:LIMIT_ZH,limitation_en:LIMIT_EN});derived.push(fact("action_priority_rank","Action priority rank",index+1,{grid_id:gridId,source_component:"ACTION_ENGINE",unit:"rank",method:"DETERMINISTIC_ACTION_PRIORITY_V1"}),fact("action_family","Action family",family,{grid_id:gridId,source_component:"ACTION_ENGINE",method:"DETERMINISTIC_ACTION_PRIORITY_V1"}),fact("action_signal_metric","Action signal metric",entry.metric,{grid_id:gridId,source_component:"ACTION_ENGINE",method:"EXISTING_WEIGHTED_CONTRIBUTION_V1"}),fact("action_signal_points","Action signal points",value,{grid_id:gridId,source_component:"ACTION_ENGINE",unit:"points",method:"EXISTING_WEIGHTED_CONTRIBUTION_V1"}));for(const id of entry.guidance_ids)derived.push(fact("action_guidance_ref","Action guidance reference",id,{grid_id:gridId,source_component:"ACTION_ENGINE",source_ref:guidance[id].url,method:"CURATED_PUBLIC_GUIDANCE_V1"}));});
  const unique=[...new Set(guidanceIds)];
  return toolResult("recommend_actions",{scope:"grid",grid_id:gridId,risk_score:Number(grid.risk_score),risk_scope:SCOPE,action_cards:cards,guidance:unique.map(id=>guidance[id]),recommendation_status:STATUS},[...underlying,...derived],cards.length);
}

export function hotspotActionsTool(limit=5):ToolResult {
  const hotspots=hotspotsTool(limit), evidence=[...hotspots.evidence], items:any[]=[], guidanceIds:string[]=[];
  for(const row of hotspots.data){const grid=getGrid(row.grid_id);const ranked=order.map((family,index)=>({family,index,value:Number(grid[catalog[family].metric])})).sort((a,b)=>b.value-a.value||a.index-b.index);const {family,value}=ranked[0],entry=catalog[family];guidanceIds.push(...entry.guidance_ids);const rowFacts=evidence.filter(item=>item.grid_id===row.grid_id&&["hotspot_rank","risk_score","population_total","dominant_weighted_contribution"].includes(item.metric));const signal=fact(entry.metric,"Top action weighted contribution",value,{grid_id:row.grid_id,source_component:"RISK_MODEL",unit:"points",method:"EXISTING_WEIGHTED_CONTRIBUTION_V1"});evidence.push(signal,fact("action_priority_rank","Top action priority rank",1,{grid_id:row.grid_id,source_component:"ACTION_ENGINE",unit:"rank",method:"DETERMINISTIC_ACTION_PRIORITY_V1"}),fact("action_family","Top action family",family,{grid_id:row.grid_id,source_component:"ACTION_ENGINE",method:"DETERMINISTIC_ACTION_PRIORITY_V1"}),fact("action_signal_metric","Top action signal metric",entry.metric,{grid_id:row.grid_id,source_component:"ACTION_ENGINE",method:"EXISTING_WEIGHTED_CONTRIBUTION_V1"}),fact("action_signal_points","Top action signal points",value,{grid_id:row.grid_id,source_component:"ACTION_ENGINE",unit:"points",method:"EXISTING_WEIGHTED_CONTRIBUTION_V1"}));items.push({hotspot_rank:row.rank,grid_id:row.grid_id,risk_score:Number(row.risk_score),population_total:Number(row.population_total),dominant_weighted_contribution:String(row.dominant_weighted_contribution),top_action_family:family,top_action_signal_metric:entry.metric,top_action_signal_points:value,supporting_evidence:[...rowFacts,signal].map(ref),recommendation_status:STATUS,effect_estimate:null});}
  evidence.push(fact("action_catalog_version","Action catalog version","M5C_ACTION_CATALOG_V1",{source_component:"ACTION_ENGINE",method:"GROUNDED_ACTION_CATALOG_V1"}),fact("recommendation_status","Recommendation status",STATUS,{source_component:"ACTION_ENGINE",method:"DETERMINISTIC_ACTION_PRIORITY_V1"}));
  const unique=[...new Set(guidanceIds)];for(const id of unique)evidence.push(fact("action_guidance_ref","Action guidance reference",id,{source_component:"ACTION_ENGINE",source_ref:guidance[id].url,method:"CURATED_PUBLIC_GUIDANCE_V1"}));
  return toolResult("recommend_actions",{scope:"hotspots",items,guidance:unique.map(id=>guidance[id]),recommendation_status:STATUS,limitation_zh:LIMIT_ZH,limitation_en:LIMIT_EN},evidence,items.length);
}
